### ISSUE TITLE
Add `resources/.keep` (or remove resources/ folder?)

### ISSUE THREAD

**Issue by HakimCassimallyBBC** [boot-clj/boot-new#30]
By default, boot-new creates a `resources/` folder with no contents, referenced from build.boot.

This means that e.g. git won't add the folder, so on next checkout, your `boot build` will fail with a confusing error message (which you likely won't understand, as you're using boot-new ;-)

We've worked around this by adding a `resources/.keep` file, but I believe we could simply have removed the directory from the build.boot instead.  Either way, the process would be made less confusing for new boot users.

**Comment by seancorfield** [comment]
Sounds like a good enhancement (to add an empty dot file).

**Comment by seancorfield** [comment]
Fixed in 0.5.1 which I just released to clojars.org.

**Comment by HakimCassimallyBBC** [comment]
Wonderful, thanks @seancorfield!

**Comment by DjebbZ** [comment]
For me it's not solved : `.keep` is an empty folder, not an empty file... So same problem, as git doesn't track empty folders.

Executed just now :

``` shell
$ boot -d boot/new new -t default -n foobar
# some output...
$ ls -la foobar/resources/
drwxr-xr-x 3 djebbz djebbz 4.0K Sep 29 16:22 ./
drwxr-xr-x 6 djebbz djebbz 4.0K Sep 29 16:22 ../
drwxr-xr-x 2 djebbz djebbz 4.0K Sep 29 16:22 .keep/
```
